// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392_BE.Repositories.Entities;

public partial class Food
{
    public int Id { get; set; }

    public string FoodId { get; set; }

    public string Name { get; set; }

    public string StoreId { get; set; }

    public int Price { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int Cate { get; set; }

    public string Image { get; set; }

    public int Status { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Store Store { get; set; }
}