// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392_BE.Repositories.Entities;

public partial class Order
{
    public int Id { get; set; }

    public string OrderId { get; set; }

    public string UserId { get; set; }

    public string SessionId { get; set; }

    public int Price { get; set; }

    public int Quantity { get; set; }

    public string StoreId { get; set; }

    public string TransactionId { get; set; }

    public int Status { get; set; }

    public TimeSpan CreatedTime { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string VoucherId { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Session Session { get; set; }

    public virtual Store Store { get; set; }

    public virtual Transaction Transaction { get; set; }

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}