// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392_BE.Repositories.Entities;

public partial class Store
{
    public int Id { get; set; }

    public string StoreId { get; set; }

    public string AreaId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int Status { get; set; }

    public string Phone { get; set; }

    public TimeSpan OpenTime { get; set; }

    public TimeSpan CloseTime { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? DeletedDate { get; set; }

    public string DeletedBy { get; set; }

    public virtual Area Area { get; set; }

    public virtual ICollection<Food> Foods { get; set; } = new List<Food>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<StoreSession> StoreSessions { get; set; } = new List<StoreSession>();
}