// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWD392_BE.Repositories.Entities;

public partial class StoreSession
{
    public int Id { get; set; }

    public string SessionId { get; set; }

    public string StoreId { get; set; }

    public virtual Session Session { get; set; }

    public virtual Store Store { get; set; }
}